### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by notpushkin** [open-eid/MOPP-Android#122]
[F-Droid] is a repository of open source software for the Android platform, alternative to Google Play. It is used by many FOSS enthusiasts (including myself :). It automatically builds applications from source, so it won't be a hassle to maintain, too.

I can submit a [request for packaging][rfp] if that's okay with you, and if you have any questions I'd be happy to answer!

[F-Droid]: https://f-droid.org/en/about/
[rfp]: https://f-droid.org/en/docs/Inclusion_How-To/

**Comment by kristelmerilain** [comment]
Thank you for the suggestion.
Currently there are no plans to publish to F-Droid.
In case of questions please contact our support via help@ria.ee.

**Comment by notpushkin** [comment]
Thanks for the response! Sad that you feel this way. If your concern is the burden of packaging for another platform, it shouldn't be too hard as 99% of the required work is done by the F-Droid community, and as I said, builds are completely automatic. The only thing we would need is ask a few questions about the libraries used and where they come from. Thank you!
